//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysTask2.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeysResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeysResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeysTask2.Config.KeysResource", typeof(KeysResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome.
        /// </summary>
        internal static string BrowserName {
            get {
                return ResourceManager.GetString("BrowserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\KeysAutomation\KeysTask2\TestData\TestData.xlsx.
        /// </summary>
        internal static string ExcelDataPath {
            get {
                return ResourceManager.GetString("ExcelDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\KeysAutomation\KeysTask2\Config\extent-config.xml.
        /// </summary>
        internal static string ExtentReportConfig {
            get {
                return ResourceManager.GetString("ExtentReportConfig", resourceCulture);
            }
        }
        
     
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace KeysTask2.Config {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   A strongly-type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeysResource_Designer {
            get {
                return ResourceManager.GetString("KeysResource_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\KeysAutomation\KeysTask2\TestReports\.
        /// </summary>
        internal static string ReportPath {
            get {
                return ResourceManager.GetString("ReportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\KeysAutomation\KeysTask2\Screenshots\.
        /// </summary>
        internal static string ScreenshotPath {
            get {
                return ResourceManager.GetString("ScreenshotPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://new-keys.azurewebsites.net/Account/Login.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
